// apps/qwik-app/src/routes/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$ } from '@builder.io/qwik-city';
import { apiClient } from '@mono/api-client';
import { formatCurrency } from '@mono/utils';
import { colors } from '@mono/ui';

export const useProducts = routeLoader$(async () => {
  const { data } = await apiClient.products.list();
  return data;
});

export default component$(() => {
  const products = useProducts();

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem' }}>
      <header style={{ borderBottom: `3px solid ${colors.primary}`, paddingBottom: '1rem', marginBottom: '2rem' }}>
        <h1 style={{ color: colors.primary }}>Qwik App</h1>
        <p style={{ color: '#666' }}>Yarn PnP Monorepo — Qwik (Resumable)</p>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1rem' }}>
        {products.value.map((product) => (
          <div
            key={product.id}
            style={{
              border: '1px solid #e5e7eb',
              borderRadius: '8px',
              padding: '1rem',
              boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
              background: 'white',
            }}
          >
            <h3 style={{ margin: '0 0 0.5rem', color: colors.primary }}>{product.name}</h3>
            <p style={{ margin: '0 0 0.5rem', fontSize: '0.875rem', color: '#6b7280' }}>{product.description}</p>
            <strong style={{ color: colors.success }}>{formatCurrency(product.price)}</strong>
          </div>
        ))}
      </div>
    </div>
  );
});

// apps/svelte-app/src/routes/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';
  import { formatCurrency } from '@mono/utils';
  import { colors } from '@mono/ui';

  export let data: PageData;
</script>

<svelte:head>
  <title>SvelteKit App - Mono</title>
</svelte:head>

<div style="font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem">
  <header style="border-bottom: 3px solid {colors.primary}; padding-bottom: 1rem; margin-bottom: 2rem">
    <h1 style="color: {colors.primary}">SvelteKit App</h1>
    <p style="color: #666">Yarn PnP Monorepo — SvelteKit (SSR)</p>
  </header>

  <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem">
    {#each data.products as product (product.id)}
      <div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); background: white">
        <h3 style="margin: 0 0 0.5rem; color: {colors.primary}">{product.name}</h3>
        <p style="margin: 0 0 0.5rem; font-size: 0.875rem; color: #6b7280">{product.description}</p>
        <strong style="color: {colors.success}">{formatCurrency(product.price)}</strong>
      </div>
    {/each}
  </div>
</div>

<style>
  :global(*, *::before, *::after) { box-sizing: border-box; }
  :global(body) { margin: 0; background: #f9fafb; }
</style>
